### ISSUE TITLE
Private folder is missing

### ISSUE THREAD

**Issue by MrSilaz** [Konafets/typo3_debugbar#24]
Hi, 
i get this error on install your Extensioion (1.3.1)

`
Fatal error: require(): Failed opening required '/home/www/......../typo3/typo3conf/ext/typo3_debugbar/Resources/Private/ExtensionArtifacts/autoload.php' (include_path='.:') in /html/typo3/typo3conf/ext/typo3_debugbar/ext_localconf.php on line 8`

You have forgot the Private folder to upload (in release 1.3.1)

BR

**Comment by Konafets** [comment]
Fixed in 5a6c6769e15333d5e0afa0b80ae0249f852a6493

**Comment by Konafets** [comment]
Can you try version 1.3.3?

**Comment by MrSilaz** [comment]
Next one ;-) i dont have any Libraries folder :-/ 

`Fatal error: require(): Failed opening required 'phar:///....../typo3/typo3conf/ext/typo3_debugbar/Resources/Private/ExtensionArtifacts/../../../Libraries/debugbar.phar/vendor/autoload.php' (include_path='.:') in /....../typo3/typo3conf/ext/typo3_debugbar/Resources/Private/ExtensionArtifacts/autoload.php on line 5`

**Comment by Konafets** [comment]
Please answer the following questions:

1. What kind is your TYPO3 installation? Composer or classical
2. How do you install this extension

**Comment by MrSilaz** [comment]
Its a classical on Mittwald.de, extension was downloaded from github and manually uploaded

**Comment by Konafets** [comment]
Any reason why you don't use the TER via the Extension Manager?

**Comment by MrSilaz** [comment]
When I tested it, the version  here in github was newer than the one in TER and here was still this #12 Error.

**Comment by Konafets** [comment]
**Short**: The latest version at TER is the same as here and contains the `Library` folder + the PHAR file.

**Some background**:
The including PHAR file in the `Library` folder is just a workaround to provide the external composer dependencies to classical TYPO3 installations since the EM is not able to install those by its own. 

I don't want to add the PHAR to the repository because it pollutes the folder and needs to be updated regularly – all things which are handled by composer. The current workflow is, that I create a release here, then I prepare the ZIP file for TER by removing all unneeded files, create the PHAR file, pack everything and upload this to TER. I am currently working on automating this part.

**Comment by MrSilaz** [comment]
Version in TER works fine, thanks :-)
